// Dados iniciais do CSV
const initialData = [
    {materia: "CONHECIMENTOS BÁSICOS", topico: "", isHeader: true},
    {materia: "Língua Portuguesa (FGV)", topico: "1. Elementos de construção do texto e seu sentido."},
    {materia: "Língua Portuguesa (FGV)", topico: "2. Gênero e tipo textual."},
    {materia: "Língua Portuguesa (FGV)", topico: "3. Coesão e coerência."},
    {materia: "Língua Portuguesa (FGV)", topico: "4. Ortografia e acentuação."},
    {materia: "Língua Portuguesa (FGV)", topico: "5. Semântica: Sinonímia, antonímia, polissemia."},
    {materia: "Língua Portuguesa (FGV)", topico: "6. Morfologia: Classes de palavras."},
    {materia: "Língua Portuguesa (FGV)", topico: "7. Sintaxe: Frase, oração, período; Termos da oração."},
    {materia: "Língua Portuguesa (FGV)", topico: "8. Pontuação."},
    {materia: "Língua Portuguesa (FGV)", topico: "9. Concordância verbal e nominal."},
    {materia: "Língua Portuguesa (FGV)", topico: "10. Regência verbal e nominal; Crase."},
    {materia: "Língua Portuguesa (FGV)", topico: "11. Figuras de linguagem e vícios de linguagem."},
    {materia: "Raciocínio Lógico-Matemático", topico: "1. Lógica Proposicional: Proposições, conectivos, tabelas-verdade."},
    {materia: "Raciocínio Lógico-Matemático", topico: "2. Equivalências e negações lógicas."},
    {materia: "Raciocínio Lógico-Matemático", topico: "3. Argumentação lógica."},
    {materia: "Raciocínio Lógico-Matemático", topico: "4. Diagramas lógicos (Conjuntos)."},
    {materia: "Raciocínio Lógico-Matemático", topico: "5. Análise Combinatória: Princípio da contagem, arranjos, permutações, combinações."},
    {materia: "Raciocínio Lógico-Matemático", topico: "6. Probabilidade."},
    {materia: "Raciocínio Lógico-Matemático", topico: "7. Problemas de raciocínio: sequências, orientação espacial/temporal."},
    {materia: "Legislação e Ética", topico: "1. Noções de Direito Administrativo: Atos, poderes, organização."},
    {materia: "Legislação e Ética", topico: "2. Noções de Direito Constitucional: Direitos e garantias fundamentais."},
    {materia: "Legislação e Ética", topico: "3. Lei de Acesso à Informação (Lei nº 12.527/2011)."},
    {materia: "Legislação e Ética", topico: "4. Lei Geral de Proteção de Dados Pessoais (LGPD - Lei nº 13.709/2018)."},
    {materia: "Legislação e Ética", topico: "5. Ética no Serviço Público."},
    {materia: "CONHECIMENTOS ESPECÍFICOS", topico: "", isHeader: true},
    {materia: "Fundamentos do Design", topico: "1. Teoria e Psicologia das Cores (Sistemas CMYK, RGB, Pantone)."},
    {materia: "Fundamentos do Design", topico: "2. Princípios da Gestalt aplicados ao design."},
    {materia: "Fundamentos do Design", topico: "3. Semiótica aplicada à comunicação visual."},
    {materia: "Fundamentos do Design", topico: "4. História do Design Gráfico."},
    {materia: "Identidade Visual e Branding", topico: "1. Conceitos de marca, identidade visual e branding."},
    {materia: "Identidade Visual e Branding", topico: "2. Processo de criação de logotipos e símbolos."},
    {materia: "Identidade Visual e Branding", topico: "3. Manual de Identidade Visual: Estrutura e aplicação."},
    {materia: "Identidade Visual e Branding", topico: "4. Aplicação de marcas em diferentes mídias (on e offline)."},
    {materia: "Tipografia", topico: "1. Classificação e anatomia dos tipos."},
    {materia: "Tipografia", topico: "2. Legibilidade e leiturabilidade."},
    {materia: "Tipografia", topico: "3. Hierarquia tipográfica."},
    {materia: "Tipografia", topico: "4. Combinação de fontes (Pairing)."},
    {materia: "Tipografia", topico: "5. Uso de tipografia em projetos editoriais e digitais."},
    {materia: "Design Editorial", topico: "1. Projeto gráfico para publicações (livros, revistas, relatórios)."},
    {materia: "Design Editorial", topico: "2. Diagramação, grids e layouts."},
    {materia: "Design Editorial", topico: "3. Formatos de papel e aproveitamento."},
    {materia: "Design Editorial", topico: "4. Infografia: Planejamento e criação."},
    {materia: "Produção Gráfica", topico: "1. Processos de impressão: Offset, digital, serigrafia."},
    {materia: "Produção Gráfica", topico: "2. Acabamentos gráficos (verniz, laminação, relevo, corte especial)."},
    {materia: "Produção Gráfica", topico: "3. Fechamento de arquivos para impressão (sangria, marcas de corte, etc.)."},
    {materia: "Produção Gráfica", topico: "4. Gerenciamento de cores e perfis de cor."},
    {materia: "Design Digital e UI/UX", topico: "1. Fundamentos de UI (User Interface) e UX (User Experience)."},
    {materia: "Design Digital e UI/UX", topico: "2. Design responsivo e adaptativo."},
    {materia: "Design Digital e UI/UX", topico: "3. Criação de layouts para websites, hotsites e landing pages."},
    {materia: "Design Digital e UI/UX", topico: "4. Produção de peças para redes sociais (posts, stories, banners)."},
    {materia: "Design Digital e UI/UX", topico: "5. Noções de HTML e CSS."},
    {materia: "Design Digital e UI/UX", topico: "6. Acessibilidade digital (WCAG)."},
    {materia: "Design Digital e UI/UX", topico: "7. Formatos de arquivo para web (JPEG, PNG, GIF, SVG, WEBP)."},
    {materia: "Softwares de Design", topico: "1. Adobe Photoshop: Tratamento de imagem, fusão, filtros, automação."},
    {materia: "Softwares de Design", topico: "2. Adobe Illustrator: Desenho vetorial, ferramentas de forma, pathfinder."},
    {materia: "Softwares de Design", topico: "3. Adobe InDesign: Diagramação, estilos, páginas-mestras, links."},
    {materia: "Softwares de Design", topico: "4. Adobe After Effects: Fundamentos de animação e motion graphics."},
    {materia: "Softwares de Design", topico: "5. Adobe Premiere: Fundamentos de edição de vídeo."},
    {materia: "Softwares de Design", topico: "6. Ferramentas de prototipação (Figma/Adobe XD) - Noções."},
    {materia: "Comunicação e Marketing", topico: "1. Comunicação institucional e mercadológica."},
    {materia: "Comunicação e Marketing", topico: "2. Planejamento de campanhas publicitárias."},
    {materia: "Comunicação e Marketing", topico: "3. Redação publicitária (títulos, slogans)."},
    {materia: "Tópicos Específicos (CPRM)", topico: "1. Princípios de Design Cartográfico."},
    {materia: "Tópicos Específicos (CPRM)", topico: "2. Geoprocessamento e Sistemas de Informação Geográfica (SIG) - Noções."},
    {materia: "PROVA DISCURSIVA", topico: "", isHeader: true},
    {materia: "PROVA DISCURSIVA", topico: "1. Estrutura da dissertação-argumentativa (padrão FGV)."},
    {materia: "PROVA DISCURSIVA", topico: "2. Análise de temas de atualidades e específicos do cargo."},
    {materia: "PROVA DISCURSIVA", topico: "3. Prática de redação (mínimo 1 por semana)."}
];